stages:
  - bootstrap
  - bootstrap_clang
  - test
  - test_perf
  - deploy

variables:
  BRANCH: "master"

bootstrap_perf:
  except:
    - ${BRANCH}
  stage: test
  tags:
    - perf
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - cp -rfp /home/aleks.tikhonov/Workspaces/runners images/.
    - docker build --network=host -t $CI_REGISTRY/${CI_PROJECT_PATH}:ubuntu-bionic_bootstrapped -f images/Dockerfile.ubuntu_perf images
    - docker push $CI_REGISTRY/${CI_PROJECT_PATH}:ubuntu-bionic_bootstrapped

build_perf:
  except:
    - ${BRANCH}
  stage: test_perf
  tags:
    - perf
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build --network=host -t $CI_REGISTRY/${CI_PROJECT_PATH}:ubuntu-bionic_built -f images/Dockerfile.ubuntu_perf_build .
    - docker push $CI_REGISTRY/${CI_PROJECT_PATH}:ubuntu-bionic_built
    - docker run --rm --network=host -i $CI_REGISTRY/${CI_PROJECT_PATH}:ubuntu-bionic_built /bin/bash -c "perf/run-tarantool-server.sh && THREADS=4 /opt/runners/sysbench-benchmarking/run.sh"
    - docker run --rm --network=host -i $CI_REGISTRY/${CI_PROJECT_PATH}:ubuntu-bionic_built /bin/bash -c "/opt/runners/tpcc-benchmarking/run.sh"
    - docker run --rm --network=host -i $CI_REGISTRY/${CI_PROJECT_PATH}:ubuntu-bionic_built /bin/bash -c "/opt/runners/ycsb-benchmarking/run.sh"
    - docker run --rm --network=host -i $CI_REGISTRY/${CI_PROJECT_PATH}:ubuntu-bionic_built /bin/bash -c "/opt/runners/nosqlbench-benchmarking/run.sh"

bootstrap_debian:
  except:
    - ${BRANCH}
  stage: bootstrap
  tags:
    - bootstrap
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - cp .travis.mk images/
    - docker build --network=host -t $CI_REGISTRY/${CI_PROJECT_PATH}:debian-stretch_bootstrapped -f images/Dockerfile.debian images
    - docker push $CI_REGISTRY/${CI_PROJECT_PATH}:debian-stretch_bootstrapped

bootstrap_lto:
  except:
    - ${BRANCH}
  stage: bootstrap
  tags:
    - bootstrap
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - cp .travis.mk images/
    - docker build --network=host -t $CI_REGISTRY/${CI_PROJECT_PATH}:debian-buster_bootstrapped -f images/Dockerfile.lto images
    - docker push $CI_REGISTRY/${CI_PROJECT_PATH}:debian-buster_bootstrapped

bootstrap_lto_clang:
  except:
    - ${BRANCH}
  stage: bootstrap_clang
  tags:
    - bootstrap
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - cp .travis.mk images/
    - docker build --network=host -t $CI_REGISTRY/${CI_PROJECT_PATH}:debian-buster_bootstrapped_clang -f images/Dockerfile.lto_clang images
    - docker push $CI_REGISTRY/${CI_PROJECT_PATH}:debian-buster_bootstrapped_clang

test_release:
  except:
    - ${BRANCH}
  image: $CI_REGISTRY/${CI_PROJECT_PATH}:debian-stretch_bootstrapped
  stage: test
  tags:
    - docker_test
  script:
    - make -f .travis.mk runtest_ubuntu

test_debug:
  except:
    - ${BRANCH}
  image: $CI_REGISTRY/${CI_PROJECT_PATH}:debian-stretch_bootstrapped
  stage: test
  tags:
    - docker_test
  script:
    - make -f .travis.mk runtest_cov_ubuntu

test_release_clang:
  except:
    - ${BRANCH}
  image: $CI_REGISTRY/${CI_PROJECT_PATH}:debian-stretch_bootstrapped
  stage: test
  tags:
    - docker_test
  variables:
    CC: clang
    CXX: clang++
  script:
    - make -f .travis.mk runtest_ubuntu

test_lto:
  except:
    - ${BRANCH}
  image: $CI_REGISTRY/${CI_PROJECT_PATH}:debian-buster_bootstrapped
  stage: test
  tags:
    - docker_test
  variables:
    CMAKE_EXTRA_PARAMS: -DENABLE_LTO=ON
  script:
    - make -f .travis.mk runtest_ubuntu

test_lto_clang:
  except:
    - ${BRANCH}
  image: $CI_REGISTRY/${CI_PROJECT_PATH}:debian-buster_bootstrapped_clang
  stage: test
  tags:
    - docker_test
  variables:
    CC: clang-8
    CXX: clang++-8
    CMAKE_EXTRA_PARAMS: -DENABLE_LTO=ON
  script:
    - make -f .travis.mk runtest_ubuntu

# No OS X workers.
#  except:
#    - ${BRANCH}
#  image: packpack/packpack:osx
#test_osx_release:
#  stage: test
#  tags:
#    - osx
#  script:
#    - make -f .travis.mk test_osx

pack_ubuntu_bionic:
  except:
    - ${BRANCH}
  image: packpack/packpack:ubuntu-bionic
  stage: deploy
  tags:
    - tarantool_ubuntu_bionic
  script:
    - git submodule update --recursive --init && git clone https://github.com/packpack/packpack.git packpack && make -f packpack/pack/Makefile -C . BUILDDIR=$PWD/build -j
