FROM registry.gitlab.com/tarantool/tarantool:ubuntu-bionic_bootstrapped_2.2.0

COPY . /opt/tarantool
WORKDIR /opt/tarantool
RUN cmake . -DENABLE_DIST=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo >cmake.log && make -j >build.log && make install >install.log
