FROM registry.gitlab.com/tarantool/tarantool:ubuntu-bionic_bootstrapped_gk4198

COPY . /opt/tarantool
WORKDIR /opt/tarantool
RUN cmake . -DENABLE_DIST=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo >cmake.log && make -j >build.log && make install >install.log
